# Site settings
title: Thomas Gadd Professional page
author: Thomas Gadd
  name: Thomas Gadd
  email: thomas.gadd.alt@gmail.com
description: "Website for all Academic and Professional things related to myself."

# Build settings
remote_theme: BDHU/minimalist
